In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [7]:
arr1 = np.array([12,34,45,56,23,23])

In [9]:
print("1D Array" , arr1)

1D Array [12 34 45 56 23 23]


In [11]:
arr2 = np.array([[12,34,45,56,23,23] , [23,34,323,45,23,45]])

In [13]:
print("2D Array" , arr2)

2D Array [[ 12  34  45  56  23  23]
 [ 23  34 323  45  23  45]]


In [19]:
z = np.zeros((2,3))

In [21]:
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
ones = np.ones((3,3))

In [27]:
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
rng = np.arange(0,10,2) # s : s : s

In [35]:
rng

array([0, 2, 4, 6, 8])

In [40]:
a = np.array([1,2,4])
b = np.array([4,6,0])


In [44]:
x = a+b

In [46]:
x

array([5, 8, 4])

In [48]:
z = a*b

In [50]:
z

array([ 4, 12,  0])

In [54]:
a[0]

1

In [56]:
a[2]

4

In [58]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

In [64]:
arr_2d[1,2]

6

In [66]:
lst = [[1, 2, 3], [4, 5, 6]]

In [72]:
lst[1][2]

6

In [86]:
data = np.array([10, 20, 30,23,23,23, 40, 50])

In [92]:
print(np.mean(data))
print(np.median(data))
print(np.min(data))
print(np.max(data))

27.375
23.0
10
50


In [94]:
np.sum(arr_2d , axis=0)

array([5, 7, 9])

In [96]:
np.sum(arr_2d , axis=1)

array([ 6, 15])

In [98]:
arr_2d.flatten()

array([1, 2, 3, 4, 5, 6])

In [119]:
arr_2d.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [107]:
list_2d = [[1, 2, 3], [4, 5, 6]]

In [115]:
flat = []
for sub in list_2d:
    for item in sub:
        flat.append(item)

In [117]:
flat

[1, 2, 3, 4, 5, 6]

In [130]:
mixedData = np.array([12,34,12,np.nan,34])

In [132]:
np.nanmean(mixedData)

23.0

In [134]:
sales = np.array([500, 200, 800, 150])

In [140]:
np.argmax(sales) + 1

3