In [2]:
import numpy as np

In [4]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])


In [10]:
arr3 = np.concatenate((arr1 , arr2),axis=0)

In [12]:
arr3

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [14]:
arr3 = arr3 = np.concatenate((arr1 , arr2),axis=1)

In [16]:
print(arr3)

[[1 2 5 6]
 [3 4 7 8]]


In [37]:
arr = np.array([1, 2, 3, 4, 5,6])


In [39]:
new_ar = np.array_split(arr,2)

In [41]:
new_ar

[array([1, 2, 3]), array([4, 5, 6])]

In [46]:
arr_3d = np.array([[[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]],
                   [[13, 14, 15, 16],
                    [17, 18, 19, 20],
                    [21, 22, 23, 24]]])

In [48]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [50]:
arr.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [54]:
arr.reshape(1,2,3,2)

array([[[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]]])

In [56]:
arr.reshape(2,1,2,3)

array([[[[ 1,  2,  3],
         [ 4,  5,  6]]],


       [[[ 7,  8,  9],
         [10, 11, 12]]]])

In [60]:
x = np.where(arr==4)

In [62]:
x


(array([3]),)

In [67]:
evens = np.where(arr%2 == 0)

In [69]:
evens

(array([ 1,  3,  5,  7,  9, 11]),)

In [71]:
odd = np.where(arr%2 == 1)

In [73]:
odd

(array([ 0,  2,  4,  6,  8, 10]),)

In [75]:
arr = np.array(['banana', 'cherry', 'apple'])

In [77]:
x = np.sort(arr)

In [79]:
x

array(['apple', 'banana', 'cherry'], dtype='<U6')

In [83]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

In [91]:
np.sort(arr)[:,::-1]

array([[4, 3, 2],
       [5, 1, 0]])

In [87]:
np.sort?

Signature:       np.sort(a, axis=-1, kind=None, order=None)
Call signature:  np.sort(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function sort at 0x1048fe480>
File:            /opt/anaconda3/lib/python3.11/site-packages/numpy/core/fromnumeric.py
Docstring:      
Return a sorted copy of an array.

Parameters
----------
a : array_like
    Array to be sorted.
axis : int or None, optional
    Axis along which to sort. If None, the array is flattened before
    sorting. The default is -1, which sorts along the last axis.
kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
    Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
    and 'mergesort' use timsort or radix sort under the covers and, in general,
    the actual implementation will vary with data type. The 'mergesort' option
    is retained for backwards compatibility.

    .. versionchanged:: 1.15.0.
       The 'stable' option was added.

order : str or list of str, 