In [3]:
import numpy as np

In [5]:
original_array = np.array([1, 2, 3, 4])

In [7]:
view_array = original_array.view()

In [11]:
print(view_array)
print(original_array)

[1 2 3 4]
[1 2 3 4]


In [13]:
view_array[2] = 90

In [15]:
print(view_array)
print(original_array)

[ 1  2 90  4]
[ 1  2 90  4]


In [21]:

original_array = np.array([1, 2, 3, 4])
copy_arr = original_array.copy()

In [24]:
print(original_array)
print(copy_arr)

[1 2 3 4]
[1 2 3 4]


In [26]:
copy_arr[2] = 100

In [28]:
print(original_array)
print(copy_arr)

[1 2 3 4]
[  1   2 100   4]


In [32]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])


In [34]:
print(arr.shape)

(2, 4)


In [36]:



d1 = np.array([12,23,34,23])

In [38]:
print(d1.shape)

(4,)


In [40]:
arr2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [42]:
arr2.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [61]:
d3 = arr2.reshape(2,3,2)

In [48]:
for item in arr2:
    print(item)

1
2
3
4
5
6
7
8
9
10
11
12


In [74]:
d2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])


In [59]:
for d1 in d2:
    for d0 in d1:
        print(d0)

1
2
3
4
5
6
7
8


In [67]:
for d2 in d3:
    for d1 in d2:
        for d0 in d1:
            print(d0)

1
2
3
4
5
6
7
8
9
10
11
12


In [70]:
for item in np.nditer(d3):
    print(item)

1
2
3
4
5
6
7
8
9
10
11
12


In [78]:
for item in np.nditer(d2[:,::2]):
    print(item)

1
3
5
7


In [80]:
arr1 =  np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [86]:
for index,item in np.ndenumerate(arr1):
    print(index , item)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6
(6,) 7
(7,) 8
(8,) 9
(9,) 10
(10,) 11
(11,) 12


In [91]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

In [93]:
x = arr1 + arr2

In [95]:
x

array([5, 7, 9])

In [99]:
z = np.concatenate((arr1, arr2))

In [101]:
z

array([1, 2, 3, 4, 5, 6])